// Generated by CoffeeScript 1.9.1
var BinarySearchTree;

BinarySearchTree = (function() {
  function BinarySearchTree() {
    this.size = 0;
    this.root_node = null;
  }

  BinarySearchTree.prototype.insert = function(value) {
    if (this.root_node != null) {

    } else {
      this.root_node = {
        value: value
      };
    }
    return this.size++;
  };

  return BinarySearchTree;

})();

module.exports = BinarySearchTree;
