// Generated by CoffeeScript 1.9.1
var BinarySearchTree;

BinarySearchTree = (function() {
  function BinarySearchTree() {
    this.size = 0;
    this.depth = 0;
    this.root_node = null;
    this.balance = 0;
  }

  BinarySearchTree.prototype.insert = function(value) {
    var cur_depth, cur_node;
    if (this.root_node != null) {
      cur_depth = 1;
      cur_node = this.root_node;
      while (cur_node.value !== value) {
        if (value < cur_node.value) {
          if (cur_node.left == null) {
            cur_node.left = {
              value: value
            };
            this.balance++;
          }
          cur_node = cur_node.left;
          cur_depth++;
        } else {
          if (cur_node.right == null) {
            cur_node.right = {
              value: value
            };
            this.balance--;
          }
          cur_node = cur_node.right;
          cur_depth++;
        }
      }
      if (cur_depth > this.depth) {
        this.depth = cur_depth;
      }
    } else {
      this.root_node = {
        value: value
      };
      this.depth = 1;
    }
    return this.size++;
  };

  return BinarySearchTree;

})();

module.exports = BinarySearchTree;
