// Generated by CoffeeScript 1.9.1
(function() {
  var Queue;

  Queue = (function() {
    var Node;

    function Queue() {
      this.size = 0;
    }

    Queue.prototype.enqueue = function(value) {
      var node;
      node = new Node(value);
      if (this.head == null) {
        this.head = node;
      }
      if (this.tail != null) {
        node.prev = this.tail;
        this.tail.next = node;
      }
      this.tail = node;
      return this.size++;
    };

    Queue.prototype.dequeue = function() {
      var node;
      node = this.head;
      this.head = this.head.next;
      if (this.head != null) {
        this.head.prev = null;
      }
      this.size--;
      return node.value;
    };

    Node = (function() {
      function Node(value1) {
        this.value = value1;
      }

      Node.prototype.next = null;

      Node.prototype.prev = null;

      return Node;

    })();

    return Queue;

  })();

  module.exports = Queue;

}).call(this);
