// Generated by CoffeeScript 1.9.1
(function() {
  var Stack;

  Stack = (function() {
    function Stack() {
      this.size = 0;
    }

    Stack.prototype.peek = function() {
      return this.head.value;
    };

    Stack.prototype.push = function(value) {
      var node;
      node = {
        value: value
      };
      if (this.head != null) {
        node.next = this.head;
      }
      this.head = node;
      return this.size++;
    };

    Stack.prototype.pop = function() {
      var node;
      if (this.head == null) {
        return null;
      }
      node = this.head;
      this.head = this.head.next;
      this.size--;
      return node.value;
    };

    return Stack;

  })();

  module.exports = Stack;

}).call(this);
